#!/usr/bin/env bash
# deploy.sh — Master deployment script for CodeGuard.
#
# Runs all infrastructure scripts in order and prints the public webhook URL
# at the end so you can configure GitHub.
#
# PREREQUISITES (run once before deploying):
#   1. Set AWS_ACCOUNT_ID and NOTIFICATION_EMAIL in infra/config.env
#   2. Create SSM parameters:
#        aws ssm put-parameter \
#          --name "/codeguard/github-webhook-secret" \
#          --value "<YOUR_WEBHOOK_SECRET>" \
#          --type SecureString --region us-east-1
#
#        aws ssm put-parameter \
#          --name "/codeguard/github-token" \
#          --value "<YOUR_GITHUB_PAT>" \
#          --type SecureString --region us-east-1
#   3. Install Docker (needed to build Lambda container images)
#   4. Install AWS CLI v2 and authenticate (aws configure / Lab credentials)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA="${SCRIPT_DIR}/infra"

# Initialise a clean state file (previous deploys may have stale IDs)
STATE_FILE="${INFRA}/state.env"
echo "# Auto-generated by deploy.sh — do not edit manually" > "${STATE_FILE}"

source "${INFRA}/config.env"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║              CodeGuard — Full Stack Deployment                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Region  : ${AWS_REGION}"
echo "  Account : ${AWS_ACCOUNT_ID}"
echo "  S3      : s3://${S3_BUCKET_NAME}"
echo ""

if [ "${AWS_ACCOUNT_ID}" = "YOUR_ACCOUNT_ID" ]; then
  echo "ERROR: Update AWS_ACCOUNT_ID in infra/config.env before deploying."
  exit 1
fi

run_step() {
  local label="$1"
  local script="$2"
  echo ""
  echo "──────────────────────────────────────────────────────────────────"
  echo "  STEP: ${label}"
  echo "──────────────────────────────────────────────────────────────────"
  bash "${script}"
}

run_step "01 — VPC, subnets, IGW, NAT Gateway, VPC endpoints" "${INFRA}/01-vpc.sh"
run_step "02 — Security groups"                               "${INFRA}/02-security.sh"
run_step "03 — S3 reports bucket + SNS alerts topic"          "${INFRA}/03-s3-sns.sh"
run_step "04 — Webhook Handler Lambda + API Gateway"          "${INFRA}/04-lambda.sh"
run_step "05 — SAST Scanner Lambda"                           "${INFRA}/05-lambda-scanner.sh"
run_step "06 — Notifier Lambda + S3 trigger"                  "${INFRA}/06-lambda-notifier.sh"
run_step "07 — CloudWatch log groups and alarms"              "${INFRA}/07-cloudwatch.sh"

# ── Summary ───────────────────────────────────────────────────────────────────
source "${STATE_FILE}"

echo ""
echo "──────────────────────────────────────────────────────────────────"
echo "  Done!"
echo "──────────────────────────────────────────────────────────────────"
echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    Deployment Complete!                         ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║  Public webhook URL:                                            ║"
echo "║    ${WEBHOOK_URL}"
echo "║                                                                  ║"
echo "║  Configure GitHub:                                              ║"
echo "║    Repo → Settings → Webhooks → Add webhook                     ║"
echo "║    Payload URL : ${WEBHOOK_URL}"
echo "║    Content type: application/json                               ║"
echo "║    Secret      : (value from SSM ${WEBHOOK_SECRET_PARAM})      ║"
echo "║    Events      : Pull requests                                  ║"
echo "║                                                                  ║"
echo "║  S3 reports bucket : s3://${S3_BUCKET_NAME}                    ║"
echo "║  SNS topic         : ${SNS_TOPIC_ARN}                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "NOTE: Check your inbox to confirm the SNS subscription before"
echo "      security alerts will be delivered."
echo ""
