#!/usr/bin/env bash
# deploy.sh — Master deployment script for CodeGuard.
#
# Runs all infrastructure scripts in the correct order and ends with a summary
# of the public webhook endpoint so you can configure GitHub.
#
# PREREQUISITES (run once before deploying):
#   1. Set AWS_ACCOUNT_ID and NOTIFICATION_EMAIL in infra/config.env
#   2. Create SSM parameters:
#        aws ssm put-parameter \
#          --name "/codeguard/github-webhook-secret" \
#          --value "<YOUR_WEBHOOK_SECRET>" \
#          --type SecureString --region us-east-1
#
#        aws ssm put-parameter \
#          --name "/codeguard/github-token" \
#          --value "<YOUR_GITHUB_PAT>" \
#          --type SecureString --region us-east-1
#   3. Install Docker (needed to build Lambda container images)
#   4. Install AWS CLI v2 and authenticate (aws configure / Lab credentials)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA="${SCRIPT_DIR}/infra"

# Initialise a clean state file (previous deploys may have stale IDs)
STATE_FILE="${INFRA}/state.env"
echo "# Auto-generated by deploy.sh — do not edit manually" > "${STATE_FILE}"

source "${INFRA}/config.env"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║              CodeGuard — Full Stack Deployment                  ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "  Region  : ${AWS_REGION}"
echo "  Account : ${AWS_ACCOUNT_ID}"
echo "  S3      : s3://${S3_BUCKET_NAME}"
echo ""

# Guard: fail early if account ID is still placeholder
if [ "${AWS_ACCOUNT_ID}" = "YOUR_ACCOUNT_ID" ]; then
  echo "ERROR: Update AWS_ACCOUNT_ID in infra/config.env before deploying."
  exit 1
fi

run_step() {
  local label="$1"
  local script="$2"
  echo ""
  echo "──────────────────────────────────────────────────────────────────"
  echo "  STEP: ${label}"
  echo "──────────────────────────────────────────────────────────────────"
  bash "${script}"
}

# ── Step 1: VPC + networking ──────────────────────────────────────────────────
run_step "VPC, subnets, IGW, NAT Gateway, VPC endpoints" "${INFRA}/01-vpc.sh"

# ── Step 2: Security groups ───────────────────────────────────────────────────
run_step "Security groups (EC2, Lambda)" "${INFRA}/02-security.sh"

# ── Step 3: S3 bucket + SNS topic ────────────────────────────────────────────
run_step "S3 reports bucket + SNS alerts topic" "${INFRA}/06-s3-sns.sh"

# ── Step 4: EC2 Nginx proxy ───────────────────────────────────────────────────
run_step "EC2 Nginx webhook proxy" "${INFRA}/03-ec2.sh"

# ── Step 5: Webhook handler Lambda ───────────────────────────────────────────
run_step "Lambda — Webhook Handler (Person A)" "${INFRA}/04-lambda.sh"

# ── Step 6: SAST scanner Lambda ──────────────────────────────────────────────
run_step "Lambda — SAST Scanner (Person B)" "${INFRA}/07-lambda-scanner.sh"

# ── Step 7: Notifier Lambda + S3 trigger ─────────────────────────────────────
run_step "Lambda — Notifier + S3 trigger (Person C)" "${INFRA}/08-lambda-notifier.sh"

# ── Step 8: CloudWatch logging + alarms ──────────────────────────────────────
run_step "CloudWatch log groups and alarms" "${INFRA}/05-cloudwatch.sh"

# ── Summary ───────────────────────────────────────────────────────────────────
source "${INFRA}/${STATE_FILE}"

echo ""
echo "╔══════════════════════════════════════════════════════════════════╗"
echo "║                    Deployment Complete!                         ║"
echo "╠══════════════════════════════════════════════════════════════════╣"
echo "║  Public webhook URL:                                            ║"
echo "║    https://${EC2_PUBLIC_IP}/webhook                             ║"
echo "║                                                                  ║"
echo "║  Configure GitHub:                                              ║"
echo "║    Repo → Settings → Webhooks → Add webhook                     ║"
echo "║    Payload URL : https://${EC2_PUBLIC_IP}/webhook               ║"
echo "║    Content type: application/json                               ║"
echo "║    Secret      : (value from SSM ${WEBHOOK_SECRET_PARAM})      ║"
echo "║    Events      : Pull requests + Pushes                         ║"
echo "║                                                                  ║"
echo "║  S3 reports bucket : s3://${S3_BUCKET_NAME}                    ║"
echo "║  SNS topic         : ${SNS_TOPIC_ARN}                          ║"
echo "╚══════════════════════════════════════════════════════════════════╝"
echo ""
echo "NOTE: If NOTIFICATION_EMAIL was set, check your inbox to confirm"
echo "      the SNS subscription before security alerts will be sent."
echo ""
